[project]
name = "SNMP-helper"
version = "0.1.0"
description = "SNMP library compatibility module"
authors = [{ name = "Anders Birkenes", email = "datagutten@datagutten.net" }]
requires-python = ">=3.9"
readme = "README.md"

[dependency-groups]
easysnmp = ["easysnmp>=0.2.6,<0.3"]
ezsnmp = ["ezsnmp>=1,<3"]
ezsnmp2 = [{ include-group = "ezsnmp" }]
netsnmp = ["netsnmp-py"]
pysnmp = ["pysnmp>=7,<8"]
dev = ["coverage[toml]>=7.10.0,<8"]

[tool.uv]
default-groups = ["ezsnmp"]

[tool.uv.sources]
netsnmp-py = { git = "https://github.com/datagutten/netsnmp-py3.git", branch = "exception_fix" }

[tool.uv.build-backend]
module-name = [
    "snmp_compat",
    "mib_parser",
]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.coverage.run]
branch = true

[tool.coverage.paths]
source = ["snmp_compat", "mib_parser"]

[tool.coverage.report]
exclude_lines = [
    "if self.debug:",
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]
