name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10','3.12' ]
        snmp-library: [ 'pysnmp', 'ezsnmp' ]

    steps:
    - uses: actions/checkout@v4

    - name: Start snmpsim
      run: docker run -d -p 161:161/udp ghcr.io/lextudio/docker-snmpsim:master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install netsnmp-py
      if: ${{matrix.snmp-library == 'netsnmp'}}
      run: |
        sudo apt-get update && apt-get -y install libsnmp-dev libczmq-dev
        python -m pip install pyzmq netsnmp-py 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry poetry-plugin-export
        poetry export -f requirements.txt --without-hashes --with ${{ matrix.snmp-library }} --with dev -o requirements.txt
        pip install -r requirements.txt

    - name: Run tests with unittest
      run: coverage run -m unittest tests.compat.test_compat
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}
        SNMPSIM_HOST: 127.0.0.1

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
