name: Run unit tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10','3.12', '3.14' ]
        snmp-library: [ 'pysnmp', 'ezsnmp', 'ezsnmp2' ]

    steps:
    - uses: actions/checkout@v6

    - name: Start snmpsim
      run: docker compose up -d snmpsim

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libsnmp-dev
      if: ${{matrix.snmp-library != 'pysnmp'}}
      run: sudo apt-get update && sudo apt-get -y install libsnmp-dev

    - name: Install libczmq-dev
      if: ${{matrix.snmp-library == 'netsnmp'}}
      run: sudo apt-get update && sudo apt-get -y install libczmq-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv coverage
        uv sync --no-default-groups --group dev --group ${{ matrix.snmp-library }}

    - name: Install ezsnmp v1
      if: ${{matrix.snmp-library == 'ezsnmp'}}
      run: uv add "ezsnmp<2"

    - name: Install ezsnmp v2 bugfix
      if: ${{matrix.snmp-library == 'ezsnmp2'}}
      run: uv add git+https://github.com/carlkidcrypto/ezsnmp.git --rev cd179620f6ea8b7d33364ea9c95c6f323d547775

    - name: Run tests with unittest
      run: uv run coverage run -m unittest tests.compat.test_compat
      env:
        SNMP_LIBRARY: ${{ matrix.snmp-library }}
        SNMPSIM_HOST: 127.0.0.1

    - uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
