name: Run unit tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10','3.12' ]
        snmp-library: [ 'pysnmp', 'ezsnmp' ]

    steps:
    - uses: actions/checkout@v6

    - name: Start snmpsim
      run: docker compose up -d snmpsim

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install netsnmp-py
      if: ${{matrix.snmp-library == 'netsnmp'}}
      run: |
        sudo apt-get update && apt-get -y install libsnmp-dev libczmq-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv[toml]
        uv sync --no-default-groups --group dev --group ${{ matrix.snmp-library }}

    - name: Run tests with unittest
      run: uv run coverage run -m unittest tests.compat.test_compat
      env:
        SNMP_LIBRARY: ${{ matrix.snmp-library }}
        SNMPSIM_HOST: 127.0.0.1

    - uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
